perf: new neovim 0.6 json api
lukas-reineke/cmp-rg pull request #19
Opened 2021-11-30 22:08 UTC by pedro757

Consider this: 

1. The new json api is apparently 2.5x faster according to the [release notes of neovim 0.6](https://github.com/neovim/neovim/commit/30fed27241cc2a8f930212375f994a7fa6c99008)
2. Only for neovim 0.6

2021-11-30 22:11 UTC, pedro757 commented
I'm just reading the release notes :)

2021-12-01 01:21 UTC, lukas-reineke commented
Thank you :rocket: 

But I would like to continue support for 0.5 for now.
Can you update the PR to use the new function when in 0.6, otherwise use the old one?

I am thinking it should be initialized in `new`
something like

```lua
source.new = function()
    local json_decode = vim.fn.json_decode
    if vim.fn.has "nvim-0.6" == 1 then
        json_decode = vim.json.decode
    end
    return setmetatable({
        running_job_id = 0,
        timer = vim.loop.new_timer(),
        json_decode = json_decode,
    }, { __index = source })
end
```

Then you can do `self.json_decode` inside the complete function

2021-12-01 18:51 UTC, pedro757 commented
Yeah, it's too soon to deprecate v0.5, although plugins like `nvim-lspconfig` have deprecated already any version lower than 0.6.

I've applied your changes.

2021-12-02 01:25 UTC, lukas-reineke requested changes
otherwise perfect, thank you

2021-12-02 01:25 UTC, lukas-reineke commented on README.md
> +> Requires Neovim 0.6+
remove this please

2021-12-02 01:50 UTC, pedro757 commented
I forgot that :G

2021-12-02 01:51 UTC, pedro757 commented on README.md
> +> Requires Neovim 0.6+
done

2021-12-02 02:28 UTC, lukas-reineke approved these changes
thank you

2021-12-02 02:28 UTC, merged